name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed 

       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install requests bs4

      - name: Running the Python script
        run: python main.py

      - name: Commit and Push The Results From Python Selenium Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git diff-index --quiet HEAD || git commit -m "GitHub Actions Results added"
         git pull origin main
         git push origin main
